### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by whyyao** [whyyao/Parle#5]
**Floating action button:**
- Start new conversation on conversation list

**WIP _Chandler_**
- [ ] Could center toasts (more professional)
- [ ] Choose language activity

**WIP _Yao_**
- [x] Possibly make the photos only load once 
- [x] Display untranslated message when click 
- [x] Notification icon

**WIP _AVAILABLE_**
- [ ] Make pictures round AF
- [ ] Delete Contacts
- [ ] Contacts in order
- [ ] Automatic refresh
- [ ] GOOGLE SIGNIN??????
- [ ] Enlarge photo when click
